# This workflow will install Python dependencies and run tests with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Easy string

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.7"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd)/easy_string_project/src/easy_string pytest
